# services:
#   postgres:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: airflow
#       POSTGRES_PASSWORD: airflow
#       POSTGRES_DB: airflow
#     volumes:
#       - postgres-db-volume:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD", "pg_isready", "-U", "airflow"]
#       interval: 5s
#       retries: 5
#     restart: always


# docker run -it \
#    -e POSTGRES_USER="root" \
#    -e POSTGRES_PASSWORD="root" \
#    -e POSTGRES_DB="ny_taxi" \
#    -v C:/Users/AsifB/Documents/data-zoomcamp/week1/docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data \
#    -p 5432:5432 \
#    --network=pg-network \
#    --name pg_db \
#    postgres:13
# configure docker container 

# docker run -it \
#   -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
#   -e PGADMIN_DEFAULT_PASSWORD="root" \
#   -p 8080:80 \
#   --network=pg-network \
#   --name pgadmin \
#   dpage/pgadmin4


URL="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-01.csv.gz"

python load_data.py \
  --user=root \
  --password=root \
  --host=localhost \
  --port=5432 \
  --db=ny_taxi \
  --table_name=green_taxi_trips \
  --url=${URL}

# docker run -it \
#   --network=pg-network \
#   taxi_ingest:v1001 \
#     --user=root \
#     --password=root \
#     --host=pg_db \
#     --port=5432 \
#     --db=ny_taxi \
#     --table_name=yellow_taxi_data \
#     --file_path="../app/yellow_tripdata_2021.csv"
